server:
  port: 8082

spring:
  application:
    name: ZhiPuRAG
  jackson:
    serialization:
      indent-output: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.ruyun: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  file:
#    name: logs/%d{yyyy-MM-dd}.log

zhipu:
  key: "your-key"
  knowledge_id: "your-id"
  prompt: "your-prompt"